### ISSUE TITLE
Ability to set a default tag for the "Start now" button

### ISSUE THREAD

**Issue by ahosgood** [MashSoftware/the-button#40]
**Is your feature request related to a problem? Please describe.**
Issue is not related to a problem

**Describe the solution you'd like**
A setting whereby you can set the default tag for new entries started by mashing the button

**Describe alternatives you've considered**
Multiple start buttons (messy!)
The dropdown is the current solution for this feature request and works

**Additional context**
Aim of this feature request is to try and make the fewest clicks required to record the most common tag

**Comment by andymantell** [comment]
I too would like this, but I would like mine to default to _None_ because I don't want or need to use the tagging functionality. Everything I do in my current role is for a single project and I have no need to know any more than that. My use-case for the button is simply to know if I am under or over time for the day / week

**Comment by ahosgood** [comment]
I think the default value is set to none but there is a bug that is not pre-populating that option when you go to edit an entry?

**Comment by andymantell** [comment]
oh yeah, you're absolutely right. If I select none on the edit screen and then save, it doesn't stick.

**Comment by matthew-shaw** [comment]
Fixed the bug with "None" not being selected on edit in a15561599fc20d3426a814ff8f76469054415954

In that sense, the "default" tag is already "None", if you just hit start now. To that end I've set it as default when manually creating a time entry too, so it's still an active choice for the user to select a tag.

My only concern with a default user created tag is that it removes that active choice and might lead to users accidentally adding more time to a tag than intended, simply because they forgot to change it to something other than the default.

Mock up of how I think it could work though: 
![image](https://user-images.githubusercontent.com/2802973/110224210-859f3400-7ed1-11eb-8aa4-79eb73467f54.png)

Thoughts/feedback? 👍
